# @author <a href="https://github.com/liyupi">UOW College Hong Kong</a>
# @from <a href="https://yupi.icu">GROUP PROJECT</a>
spring:
  application:
    name: springboot-init
  # Default dev environment
  profiles:
    active: dev
  # support swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session config
  session:
    # todo  cancel comments start separate session(config Redis first)
    # store-type: redis
    # 30 days
    timeout: 2592000
  # 数据库配置
  # todo change
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bi_db
    username: root
    password: 123456
  # Redis config
  # todo change
#  redis:
#    database: 1
#    host: localhost
#    port: 6379
#    timeout: 5000
#    password: 123456
  # Elasticsearch config
  # todo change
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
  # 文件上传
  servlet:
    multipart:
      # size limit
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api
    # cookie 30days
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
# Wechat
wx:
  # todo need to change
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo need to change
  open:
    appId: xxx
    appSecret: xxx
# todo need to change
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
# api config
knife4j:
  enable: true
  openapi:
    title: "api document"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.yupi.springbootinit.controller

# DeepSeek配置
deepseek:
  api:
    key: sk-b463537c0f6a4266ad2de8563ee9a15d
    url: https://api.deepseek.com/v1/chat/completions

